# Generated by Django 3.1.1 on 2020-11-20 21:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='growthInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(blank=True, default='Invest-Plan', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1000000000000000055511151231257827021181583404541015625')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('time_length', models.IntegerField(default=10)),
                ('end_result', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.monetaryuser')),
            ],
        ),
    ]
