# Generated by Django 3.1.1 on 2020-11-20 21:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='monetaryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(blank=True, default='Record', max_length=200)),
                ('category', models.CharField(choices=[('Outcome', (('expenses', 'Expenses'), ('upkeep', 'Upkeep'), ('unforeseen', 'Unforeseen'), ('Goal Complete', 'Goal Complete'), ('Investment', 'Investment'))), ('Income', (('monthly income', 'Monthly Income'), ('dividents', 'Dividents'), ('other', 'Other')))], default='Outcome', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.monetaryuser')),
            ],
        ),
    ]
