# Generated by Django 3.1.1 on 2020-11-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20201129_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetaryrecord',
            name='category',
            field=models.CharField(choices=[('Outcome', (('expenses', 'Expenses'), ('upkeep', 'Upkeep'), ('unforeseen', 'Unforeseen'), ('Goal Complete', 'Goal Complete'), ('Investment', 'Investment'), ('Saving tipped', 'Saving tipped'))), ('Income', (('monthly income', 'Monthly Income'), ('dividents', 'Dividents'), ('saving funds', 'Saving Funds'), ('Investment Cash', 'Investment Cash'), ('other', 'Other')))], default='Outcome', max_length=200),
        ),
    ]
