# Generated by Django 3.1.1 on 2020-11-20 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='monetaryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Username', max_length=200, null=True)),
                ('worth', models.DecimalField(decimal_places=2, default=10.0, max_digits=7)),
                ('warning_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=7)),
                ('email', models.EmailField(default='mail@mail.mail', max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile-default.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('page', models.CharField(choices=[('HOME', 'HOME'), ('RECORDS', 'RECORDS'), ('GOALS', 'GOALS'), ('SAVINGS', 'SAVINGS'), ('INVESTMENTS', 'INVESTMENTS'), ('CALENDAR', 'CALENDAR'), ('GRAPH', 'GRAPH'), ('SETTINGS', 'SETTINGS'), ('NAVIGATION', 'NAVIGATION'), ('ABOUT', 'ABOUT')], default='HOME', max_length=200)),
                ('details', models.CharField(blank=True, default='BugReport', max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.monetaryuser')),
            ],
        ),
    ]
