# Generated by Django 3.1.1 on 2020-11-22 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monetaryuser',
            old_name='worth',
            new_name='min_worth',
        ),
    ]
