# Generated by Django 3.1.1 on 2020-11-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201121_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='monetaryuser',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=7),
        ),
    ]
