# Generated by Django 3.1.1 on 2020-11-20 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='monetaryGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(default='Goal', max_length=200)),
                ('category', models.CharField(choices=[('Small Goal', 'Small Goal'), ('Liability Goal', 'Liability Goal'), ('Life Goal', 'Life Goal'), ('Investment Goal', 'Investment Goal')], default='Small Goal', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.monetaryuser')),
            ],
        ),
        migrations.CreateModel(
            name='completedmonetaryGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(default='Completed-Goal', max_length=200)),
                ('category', models.CharField(choices=[('Small Goal', 'Small Goal'), ('Liability Goal', 'Liability Goal'), ('Life Goal', 'Life Goal'), ('Investment Goal', 'Investment Goal')], default='Small Goal', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.monetaryuser')),
            ],
        ),
    ]
